Используя метод вращений, найти собственные значения и собственные векторы матрицы A с погрешностью $ \varepsilon = 0.01$

$$A=\begin{pmatrix}
-1 & 3 & 4 \\ 
 3 & 5 &-1 \\ 
 4 &-1 &-5
\end{pmatrix}$$

In [7]:
import numpy as np
import math
from copy import deepcopy
            

def max_diag(a): # функция нахождения максимального элемента в матрице
    m = max(abs(a[0][1]), abs(a[0][2]), abs(a[1][2]))
    if m == abs(a[0][1]):
        return m, 0, 1
    elif m == abs(a[0][2]):
        return m, 0, 2
    elif m == abs(a[1][2]):
        return m, 1, 2
    
def tsum(A):     # функция проверки eps условия
    sum=0
    for i in range(len(A)):
        for j in range(len(A)):
            if i != j:
                sum += A[i][j]**2
    return math.sqrt(sum)

def eigenv(a, eps): # функция нахождения собственных значений с заданной точностью eps
    fi=0 # угол поворота
    sin=0 # sin(fi)
    cos=0 # cos(fi)
    X=np.eye(3, 3)
    A = a
    maxdiag, i, j = max_diag(A)
    summ = 100
    k=0
    while summ > eps:
        fi = math.atan(2*A[i][j]/(A[i][i] - A[j][j]))/2
        #print("fi =", fi)
        sinfi = math.sin(fi)
        cosfi = math.cos(fi)
        H = np.eye(3, 3)
        H[i][i] = cosfi
        H[i][j] = sinfi*(-1)
        H[j][i] = sinfi
        H[j][j] = cosfi
        #print("A=\n",A)
        #print("H^T=\n", H.T)
        #print("H=\n", H)
        A = H.T.dot(A).dot(H)
        X = X.dot(H)
        
        h = np.eye(3, 3)
        for i in range(len(h)):
            h[i][i] = A[i][i]
        print("A =\n", A)
        print("X =\n", X)
        print("Aii =\n", h)
        print("Aii * X =\n", h.dot(A))
        #print("\nA - (Xii * A) =\n", A - h.dot(A)) 
        print("\nA ===== =\n", A.dot(X) - h.dot(X))
        k += 1
        maxdiag, i, j = max_diag(A)
        summ = tsum(A)
    return A, X

def check(B, A, x):
    print()
    for i in range(len(A)):
        buf = A.dot(x[:, i]) - x[:, i] * B[i][i]
        print("check lambda"+str(i+1), buf)
    
A=np.array([[-1, 3, 4], [3, 5, -1], [4, -1, -5]])
eps = 0.001

B, x = eigenv(A, eps)

print("\nСобственные значения:\nL1 =", B[0][0])
print("L2 =", B[1][1])
print("L3 =", B[2][2])

print("\nСобственные векторы:")
print("x1 =", x[:, 0])
print("\nx2 =", x[:, 1])
print("\nx3 =", x[:, 2])

#print(A)
print()
print(x)

check(B, A, x)

A =
 [[ 1.47213595e+00  2.02622131e+00  4.44089210e-16]
 [ 2.02622131e+00  5.00000000e+00 -2.42784414e+00]
 [ 0.00000000e+00 -2.42784414e+00 -7.47213595e+00]]
X =
 [[ 0.85065081  0.         -0.52573111]
 [ 0.          1.          0.        ]
 [ 0.52573111  0.          0.85065081]]
Aii =
 [[ 1.47213595  0.          0.        ]
 [ 0.          5.          0.        ]
 [ 0.          0.         -7.47213595]]
Aii * X =
 [[ 2.16718427e+00  2.98287325e+00  6.53759693e-16]
 [ 1.01311066e+01  2.50000000e+01 -1.21392207e+01]
 [ 0.00000000e+00  1.81411815e+01  5.58328157e+01]]

A ===== =
 [[ 2.22044605e-16  2.02622131e+00  3.33066907e-16]
 [ 4.47213595e-01  0.00000000e+00 -3.13049517e+00]
 [ 0.00000000e+00 -2.42784414e+00  0.00000000e+00]]
A =
 [[ 1.47213595e+00  1.99140963e+00  3.73979255e-01]
 [ 1.99140963e+00  5.45594002e+00  1.11022302e-16]
 [ 3.73979255e-01  0.00000000e+00 -7.92807597e+00]]
X =
 [[ 0.85065081  0.09703408 -0.51669874]
 [ 0.          0.98281941  0.1845698 ]
 [ 0.52573111 -0.157

In [26]:
h = np.eye(3, 3)
for i in range(len(h))
    h[i][i] = A[i][i]


array([[-1,  3,  4],
       [ 3,  5, -1],
       [ 4, -1, -5]])